//Types for All Articles 
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

//Types for Comments by Article ID
export const FETCH_COMMENTS_BY_ART_ID_SUCCESS = 'FETCH_COMMENTS_BY_ART_ID_SUCCESS';
export const FETCH_COMMENTS_BY_ART_ID_FAILURE = 'FETCH_COMMENTS_BY_ART_ID_FAILURE';