//Types for All Articles 
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

//Types for Articles by Article ID
export const FETCH_ARTICLES_BY_ART_ID_SUCCESS = 'FETCH_ARTICLES_BY_ART_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ART_ID_FAILURE = 'FETCH_ARTICLES_BY_ART_ID_FAILURE';

//Types for Comments by Article ID
export const FETCH_COMMENTS_BY_ART_ID_SUCCESS = 'FETCH_COMMENTS_BY_ART_ID_SUCCESS';
export const FETCH_COMMENTS_BY_ART_ID_FAILURE = 'FETCH_COMMENTS_BY_ART_ID_FAILURE';

//Types for All Topics
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST'
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS'
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE'

//Types for Topic Articles by Topic ID (topic type)
export const FETCH_ARTICLES_BY_ID_SUCCESS = 'FETCH_ARTICLES_BY_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ID_FAILURE = 'FETCH_ARTICLES_BY_ID_FAILURE';

//Types for adding/deleting Comments
export const ADD_COMMENTS_SUCCESS = 'ADD_COMMENTS_SUCCESS';
export const ADD_COMMENTS_FAILURE = 'ADD_COMMENTS_FAILURE';
export const DELETE_COMMENTS_SUCCESS = 'DELETE_COMMENTS_SUCCESS';
export const DELETE_COMMENTS_FAILURE = 'DELETE_COMMENTS_FAILURE';

//Types for editing votes by Article ID
export const EDIT_VOTE_COUNT_BY_ART_ID_SUCCESS = 'EDIT_VOTE_COUNT_BY_ART_ID_SUCCESS';
export const EDIT_VOTE_COUNT_BY_ART_ID_FAILURE = 'EDIT_VOTE_COUNT_BY_ART_ID_FAILURE'; 

//Types for editing votes by Comment ID
export const EDIT_VOTE_COUNT_BY_COMMENT_ID_SUCCESS = 'EDIT_VOTE_COUNT_BY_COMMENT_ID_SUCCESS';
export const EDIT_VOTE_COUNT_BY_COMMENT_ID_FAILURE = 'EDIT_VOTE_COUNT_BY_COMMENT_ID_FAILURE'; 

//Types for fetching all users
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

//Types for fetching user data by username
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';