//Types for All Articles 
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

//Types for Articles by Article ID
export const FETCH_ARTICLES_BY_ART_ID_SUCCESS = 'FETCH_ARTICLES_BY_ART_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ART_ID_FAILURE = 'FETCH_ARTICLES_BY_ART_ID_FAILURE';

//Types for Comments by Article ID
export const FETCH_COMMENTS_BY_ART_ID_SUCCESS = 'FETCH_COMMENTS_BY_ART_ID_SUCCESS';
export const FETCH_COMMENTS_BY_ART_ID_FAILURE = 'FETCH_COMMENTS_BY_ART_ID_FAILURE';

//Types for All Topics
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST'
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS'
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE'

//Types for Topic Articles by Topic ID (topic type)
export const FETCH_ARTICLES_BY_ID_SUCCESS = 'FETCH_ARTICLES_BY_SLUG_SUCCESS';
export const FETCH_ARTICLES_BY_ID_FAILURE = 'FETCH_ARTICLES_BY_SLUG_FAILURE';

